<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE raiz [
	<!ELEMENT raiz (a,b,c)+>
	<!ELEMENT a (#PCDATA)>
	<!ELEMENT b (#PCDATA)>
	<!ELEMENT c (#PCDATA)>
]>
<raiz>
	<a>Etiqueta a</a>
	<b>Etiqueta b</b>
	<c>Etiqueta c</c>
	<a></a>
	<b></b>
	<c></c>
</raiz>
